### ISSUE TITLE
Indices

### ISSUE THREAD

**Issue by Philmod** [mikhail-angelov/mongo-unit#16]
Hey,

What's the best way to apply mongo indices to a newly started instance?

Cheers,
Philmod

**Comment by mikhail-angelov** [comment]
if you are using mongoose, I think common solution will be specify indexes at schema, and mongoose call ensureIndex automatically

**Comment by Philmod** [comment]
I don't use `mongoose` unfortunately. I may add a new method to create the indices. Tell me if you have any advice or idea.

**Comment by mikhail-angelov** [comment]
probably this one is completed
