### ISSUE TITLE
ObjectId on initDb

### ISSUE THREAD

**Issue by felipeplets** [mikhail-angelov/mongo-unit#20]
In my case I need to use initDb to initialize a test database with proper ObjectIds. When calling a JSON with ObjectID NodeJS will give an error ```Unexpected token O in JSON at position XX```. I understand the error and why this can't be achieved in this way. 

My proposed solution would be to pass the file path as a parameter on the initDb method, we can test the testData parameter and check if it is a string to then require it as a JS module. When executing its content we can require('mongodb') and have mongo.ObjectId available. Then the required module can export the processed array and in the initDb we import it to the database. Seems easy and clean to be implemented. 

@mikhail-angelov what do you think about it? Would you be interested in a PR with that behaviour?

**Comment by mikhail-angelov** [comment]
I think it's not needed for this library, you can require test data from .js file and have all functions and data processing outside of this lib

like this
```
const testData = require('testData.js')
```
//testData.js
```
const nongodb = require('mongodb')
module.exports = {
  user:[{_id: mongodb.ObjectId('1111'), name: 'test}]
}
```

**Comment by felipeplets** [comment]
Sure, you are right. It worked for me. I will drop the PR. 
Thanks for helping!
