### ISSUE TITLE
load(), clean() and drop() do not close connection

### ISSUE THREAD

**Issue by akoptelov** [mikhail-angelov/mongo-unit#4]
These functions leave database in connected state. By default mongo driver tries to reconnect if connection is lost. That makes mocha v4 test suite wait after all tests complete.

**Comment by akoptelov** [comment]
This is a test that will hang for some time when running with mocha v4: 
```var mongoUnit = require('mongo-unit');
describe('Test suite won\'t finish right after the last test', function () {
    before(function () {
        return mongoUnit.start()
            .then(() => mongoUnit.load({db: {data: true}}));
    });

    it('dummy test', function () {});

    after(function () {
        return mongoUnit.stop();
    });
    
});
````

**Comment by mikhail-angelov** [comment]
released mongo-unit@1.3.2

**Comment by Philmod** [comment]
I still see the problem

**Comment by mebibou** [comment]
I am using `mongo-unit@1.3.4` and this code in `prepare.js`:
```
const prepare = require('mocha-prepare');
const mongoUnit = require('mongo-unit');

prepare(done => {
  mongoUnit.start()
    .then(testMongoUrl => (process.env.MONGODB_URL = testMongoUrl))
    .then(() => done());
}, done => {
  mongoUnit.drop()
    .then(()=> mongoUnit.stop())
    .then(() => done());
});
```
and in my unit test I use this:
```
import { initDb, dropDb } from 'mongo-unit';

describe('test' => {
  beforeEach(async () => {
      await initMongoDb(testMongoUrl); // mongoose.connect and load models
      await initDb(testMongoUrl, fixtures);
    });

    afterEach(async () => {
      await dropDb(testMongoUrl);
    });
  ...
```

After all tests are complete, and I see the `91 passing (172ms)` line, it takes around 30s before the process stops. What am I doing wrong?

**Comment by Philmod** [comment]
@mebibou You probably have an open connection, maybe from your code?

**Comment by Philmod** [comment]
I don't think `dropDb` closes the connection ([code](https://github.com/mikhail-angelov/mongo-unit/blob/master/index.js#L156))

**Comment by mebibou** [comment]
No but [stop](https://github.com/mikhail-angelov/mongo-unit/blob/master/index.js#L96) does. I've tried
```
await mongoUnit.stop();
await mongoUnit.drop();
```
but that throws an exception and still hangs, or just one of these 2 commands and it always hangs.

@mikhail-angelov what is the correct way to disconnect so that the tests don't hang at the end?

**Comment by mikhail-angelov** [comment]
Ok

First we need to make sure all clients are disconnected from db

Like

const MongoClient = require('mongodb').MongoClient

let database, client

 MongoClient.connect(
    process.env.DATABASE_URL,
    (err, dbClient) => {
      if (!err) {
        client = dbClient
        database = client.db()
      }
    }
  )

.. do staff, then

client.close()

second stop db

mongoUnit.stop()

nothing else

check examples

**Comment by mebibou** [comment]
@mikhail-angelov oh I think I got it, is it because I use both `initDb` and `dropDb` that both do NOT close the connection while every other method does?

**Comment by mikhail-angelov** [comment]
It make sense

**Comment by mebibou** [comment]
yes confirmed, just made [those changes](https://github.com/mikhail-angelov/mongo-unit/pull/19) and it didn't hang anymore
