### ISSUE TITLE
Allow to start Server as a Replica Set

### ISSUE THREAD

**Issue by tochoromero** [mikhail-angelov/mongo-unit#42]
In order to be able to Unit Test code that makes use of the new MongoDB transaction support, the MongoDB Memory Server needs to be started as a Replica Set.

We need a new `useReplicaSet` option added to the `start` function to indicate we want to start the MongoDB Memory Server as a Replica Set.

**Comment by georgeben** [comment]
I also need this functionality. Please would this be added @mikhail-angelov ? Thank you so much
