### ISSUE TITLE
Specify MongoDB Version

### ISSUE THREAD

**Issue by roberto-dynamix** [mikhail-angelov/mongo-unit#8]
Nice library!

Is it possible to specify which mongodb version is to be used?

Using always the lastest version, one day it will break the tests...

**Comment by sesm** [comment]
Could you please elaborate?
This project depends on 2.2.x Mongo DB driver, which is pretty specific (` "mongodb": "~2.2.31",` in `package.json`)

**Comment by roberto-dynamix** [comment]
Sorry, I don't remember. Probably I wanted support for mongodb driver 3.0.10 (it's a different request) and then maybe some kind of configuration would be needed. I will close/cancel the issue and try to specify better next time. Thank you.

**Comment by sesm** [comment]
@roberto-dynamix Thank you! Feel free to open a new issue for 3.x.x driver support.
